"""empty message

Revision ID: 3e0d67c04127
Revises: acf18a0528d0
Create Date: 2017-07-23 15:58:16.071391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0d67c04127'
down_revision = 'acf18a0528d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Login', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Login', 'password_hash')
    # ### end Alembic commands ###
